version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - hotels_network

networks:
  hotels_network:
    external: true 