version: '3.7'

services:
  auth_db:
    hostname: auth_db
    image: postgres:16
    container_name: auth_db
    ports:
      - "1337:5432"
    env_file:
      .env
    networks:
      - auth_network

  auth_service:
    hostname: auth_service
    build:
      context: .
    container_name: auth_service
    ports:
      - "8000:8080"
    env_file:
      - .env
    depends_on:
      - auth_db
      - prometheus
    networks:
      - auth_network

  prometheus:
    image: prom/prometheus:latest
    container_name: auth_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - auth_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    container_name: auth_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - auth_network
    depends_on:
      - prometheus

networks:
  auth_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: