version: '3.7'

services:
  auth_db:
    hostname: auth_db
    image: postgres:16
    container_name: auth_db
    ports:
      - "1337:5432"
    env_file:
      .env

  redis:
    hostname: redis
    image: redis:7
    container_name: auth_redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
    container_name: auth_celery_worker
    command: bash -c "cd src && celery -A core.celery_app worker -l info -Q emails"
    env_file:
      - .env
    depends_on:
      - redis
      - auth_db

  flower:
    build:
      context: .
    container_name: auth_flower
    command: bash -c "cd src && celery -A core.celery_app flower --port=5555"
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker

  auth_service:
    hostname: auth_service
    build:
      context: .
    container_name: auth_service
    ports:
      - "8000:8080"
    env_file:
      - .env
    depends_on:
      - auth_db
      - redis
      - celery_worker